let input = `qcsnyvpigkxmrdawlfdefotxbh
qcsnyvligkymrdawljujfotxbh
qmsnyvpigkzmrnawzjuefotxbh
qosnyvpigkzmrnawljuefouxbh
qcsnhlpigkzmrtawljuefotxbh
qcsnyvpigkzmrdapljuyfotxih
qcsnbvpiokzmrdawljuerotxbh
qcfnyvmigkzmrdawljuefotdbh
qcsnynpigkzmrdawljuefptxbp
qcsgyapigkzmrdawljuafotxbh
qcsnyvpigkzmrdapljueeotibh
qcfnyvpigkzmndawljuwfotxbh
qzsayvpigkzmrdawijuefotxbh
qcsnsvpiekzmrdawljfefotxbh
ncsnyvpigkzmrdaaljuefotxzh
qssnyvpigkzmrdawljuefotobg
qcshyipigkzmrdajljuefotxbh
qcsnyvtigkzmrdawljgeaotxbh
qcsnkvpxgkzmrdawljuefltxbh
qcsnyvpiikzmrdawljuwfoqxbh
qcsnybpigwzmqdawljuefotxbh
qcsiyvpipkzbrdawljuefotxbh
qldnyvpigkzmrdzwljuefotxbh
qcsnyvpwgkzcrdawljuefmtxbh
qcsnyvnigkzmrdahmjuefotxbh
qcsnydpigkzmrdazljuefotxnh
qcsqyvavgkzmrdawljuefotxbh
ucsnyvpigkzmrdawljuefocxwh
qcsnivpigrzmrdawljuefouxbh
tcsnyvpibkzmrdawlkuefotxbh
qcstytpigkzmrdawsjuefotxbh
qcynyvpigkzmrdawlluefotjbh
qcstyvpigkqrrdawljuefotxbh
icsnyvpizkzmrcawljuefotxbh
qcsnyvpimkzmrdavljuezotxbh
qvsnoupigkzmrdawljuefotxbh
qcsnyvpigkzmrdawwjuefftxgh
qcpnyvpijkzmrdvwljuefotxbh
qcsnyvpigkzmxdakdjuefotxbh
jcsvyvpigkqmrdawljuefotxbh
qcwnyvpigczmrsawljuefotxbh
qcsnyvpdgkzmrdawljuefoixbm
qysnyvpigkzmrdmwljuefotxbp
qcsnavpigkzmrdaxajuefotxbh
qcsfkvpigkzmrdawlcuefotxbh
qcsnyvpigkvmrdawljcefotpbh
qcsnyvpiqkkmrdawlvuefotxbh
qhsnyvpigkzmrdawnjuedotxbh
qasnlvpigkzmrdawljuefotxkh
qgsnyvpigkzmrdabpjuefotxbh
jcsnyvdigkzmrmawljuefotxbh
qcsnivpigkzmrdawljuefonxth
qcsnyjpigkzmrdawljgefotxmh
qcstyvpigkzmrdacljuefovxbh
qcsnvvpigkzmrdawljuewotrbh
qcsnyvaigdzmrdawljueuotxbh
qcsnyvpegkzmwdawljzefotxbh
qcsnevpngkzmrdawlouefotxbh
qcsnuvpigozmrdawljuefotdbh
qgsnyvpigkzmqdayljuefotxbh
qcsnyvpigkzmrdcwdjuofotxbh
qcnnyvpigkzmrzawljuefstxbh
qlsgyvpigkzmrdtwljuefotxbh
qcsnyfpigkzlroawljuefotxbh
qcsnkvwigkzmrdowljuefotxbh
qcsnrvpigkzmrdawljuvfltxbh
qcsnyvpigkzvreawljuefotxmh
qcsrgvpigkzmrdawliuefotxbh
qysnyvpigkzmrdawlxaefotxbh
qcsnyvpigizmrdlwljuefotxbi
qzsnyvpitkzmrdawljuefbtxbh
qzgnyvpigkzmrdawljuefotxih
qcsnyvpigkzmrdawlguefvtxbb
qcsnyvpigkzmidawljuefouxjh
qksnyvpigkzmrdawlruefotxhh
qcsnyvpinkzmrdaaljuefotxah
qcsnxvpigkzjrdawljuefhtxbh
qcsnyvpigkzardawlgueuotxbh
qcsnyvpiakzmrdpwljuefotxbt
qcsnyvpigkzmrdawkjuefotxgb
qcsnyvpigkzmrdawljuehocsbh
qcsnsvpigktmrdawljuefotxvh
qusnrvpigkzrrdawljuefotxbh
qcsnyhiigkzmrdawrjuefotxbh
qcsnavpigkzmrdawlfuefotxbz
qcsnyvpigkzmmdamsjuefotxbh
qcsnyvzigkzmrdcwljmefotxbh
qcsnyvpigkzmriawljuefotbbe
qcsnyvpigksmrdawljaefotxbd
qcsnyvpigkzfrdawljuefoxxmh
qcsnyvpygkrmrdawljuefotxbi
qcsngvwigfzmrdawljuefotxbh
qcsnyvpigkmkrdauljuefotxbh
qcsnyvpigxzmrdgwljuefwtxbh
qconyapigkzmrdaxljuefotxbh
qcsnydpigkzwrdawljulfotxbh
qcsnyvpimkzmmdawljuefotxch
qcsnkspigkzmrdawgjuefotxbh
qcsnyvpigkzmrdhwljfefbtxbh
qcsnyipijkztrdawljuefotxbh
qcseyvpigkrhrdawljuefotxbh
qcsnyvpivkzmrdawljuefottbb
qcsnyvpigkzmrdawlouefcjxbh
qcsnyvpigkzmrgayljuefotxbm
qcsnyvpvgkzmrdawrjujfotxbh
qcsnyvpigkzmndawljuefqtxch
qcsnyvpigbzmrdawljuefotibg
qcsnyvpigkzmseawljuefotxbv
qcsnwvpigkzmraawnjuefotxbh
mcsnyvpiqkzmrdawljuefotlbh
bcsnyvpigczmrdmwljuefotxbh
qcsnyvpigkzmrtawljuegntxbh
qcsnyvpijkzmrdawlmrefotxbh
qdsnyvpfgkzmrdawljuekotxbh
qcsnyvpigkzmrdawcjfegotxbh
qcslyvphgkrmddawljuefotxbh
qcsnyvpigkzmsdawkjuefojxbh
qzsnyvpigkzmrzawljuefmtxbh
qcsnyvpqgkzmcdawljuefttxbh
qcsnyvpbgkpmrdawljuefoqxbh
qcsnyvpigkemrdywljmefotxbh
qcsnyypigkzmrdawljmefotxwh
jcsnyvhwgkzmrdawljuefotxbh
qcsnyvpigkzmrdawljurlotxwh
qcsnnvpigzzmrdawljuefotwbh
hcsnyvpigkzmrdarljuefitxbh
qcsnyvpilkzmrfawljuefotsbh
qcsnynpigkzmldawijuefotxbh
qcsnyvpkgkjmrdawljuefotxlh
qcsnylpigkzprdawljgefotxbh
qcsnyvpigkzmrrawljnefohxbh
qcsnivpigkzmrqawlbuefotxbh
qcsgyvpigkzmrfawljuefotbbh
qccuyvpigkzmrdawyjuefotxbh
gcsnyvpigkzjrdawljuefotxby
qcsmyvpiekzbrdawljuefotxbh
qcsnyvpzgkrmrdawljuefotxbs
qesnyvpigkzmpdqwljuefotxbh
qcsnyvpigqzmrdawljuefutibh
qcdnyvpigkzirdawljfefotxbh
qcsnyvpiukzmrcrwljuefotxbh
qcsnbvpickzmrdswljuefotxbh
qcsnyvpighzmrpadljuefotxbh
qccnyvpigkzmrdawljudxotxbh
qcsnyvpigkzmrdabljuesotxlh
qcsnyvpigkzmrrawlruefozxbh
qconyzpigkzmrdawljuefotjbh
qclnyvpigkzmrdxwljuefotbbh
qcsnygpigkzmrdawlhuefooxbh
qcsnyvpigkzmvdawljuefntxnh
qcskyvpigkzmreawljuefotubh
qrsnyvpxgkzmrdawljuefotxbz
qclnyvpigtamrdawljuefotxbh
qcsnyvpigkzmrdawojxefoyxbh
qcsnyvpinkzmrdakljuwfotxbh
qcsnyvpiykzmedawljuefgtxbh
qcsayvpigkcmrdawijuefotxbh
qcsnyvuiekzmrdamljuefotxbh
qcdnyvpigkzmrdawnjuefoxxbh
qcsnfvpwgszmrdawljuefotxbh
qcsnycpigkzmrdawljqefotxih
qcslyvphgkrmrdawljuefotxbh
ecsnyvpigkzmrdawykuefotxbh
qcsayvpigkzmraawljuekotxbh
qcsnyvpigkdmrdawljuewofxbh
qcznyvpigkzqrdawljuefotxnh
qcsnyvplgkzmrdawljiefotlbh
qcsnyvpigkzmroewljuefotbbh
qcvnyvpigkzvrdawujuefotxbh
qcanyypigkzmrdaeljuefotxbh
qcsnyvwigkzmrdewljuefotxqh
qcsryvpigkvmrdawljuefotabh
pcsnyvpigkwmrdawljueforxbh
qcsncvpigkzmrdawljuefotwmh
qcsnyvpigozmrdawljudfozxbh
qcsnynpigkzmrbawhjuefotxbh
qcsnyvuigkzmrqawljuefotxch
qcsnyvpickzmrdawljueeofxbh
qcsnyvpigkzgrdawljueiouxbh
qcsnyvpigkztrdawljuxnotxbh
qcsnyvpigwzvrdawljfefotxbh
qcsnyvpilkzmrdawljuefotxcz
qcsnjvpigkzmrdawljuefoywbh
qhsnyvpigyzmrdawljuhfotxbh
qcsnyvpirkzmfdawljuffotxbh
qcsjyvpigkzmvdawljuefotxzh
qcszivpirkzmrdawljuefotxbh
qwsnyvpigkzmtdawljuefetxbh
qcrntvpigkzordawljuefotxbh
qrsnyvpigkzmsdawljrefotxbh
qcsnyviivkzmrdazljuefotxbh
ecsnyvpigkzmrdawyjuefotxbw
qnsnyvpkgkzmrdawljueqotxbh
qcsyyppigkzmrdawljuefotxba
qcsnyvpigkzhrdpwljuefouxbh
ucsnyvpigkzmrdawojuefouxbh
qysnyvpigkzmrdawljukfotxbd
qcjnyvpigkzmrdalljfefotxbh
fcsnyapigkmmrdawljuefotxbh
qcnnkvpigkzmrdawljuefctxbh
ocsnyvpigkzmsdawljuefotxbl
qcsnyvpiakomrdawpjuefotxbh
qcsnyvpigkzmrdawljvefbtxwh
qcsnuvpigkzmvdfwljuefotxbh
qcsnyapihkzmrdagljuefotxbh
qzsnyvpigkzmrdawtjuefotxgh
qcsnyvpigkzmrdawljuefomyah
ocsnyvpigkzqrdawljuefotxbt
qnsnyvpigkzmrdawljvevotxbh
icsnyvpigkzmrdawljuefntxbt
qcsnyvpigkzdrdawljuefotbbm
scsnyvpigkzmrgawljuofotxbh
qcsnydpigkzmrdowljuefotkbh
qcsnyvtikkzmrdawljuefolxbh
qcsiyvpigkcmrddwljuefotxbh
qyrnyvpigkzmodawljuefotxbh
pcsndvpfgkzmrdawljuefotxbh
qcsnyvkigkhmriawljuefotxbh
qcsnyvpigkzmsdmwlkuefotxbh
dosnyvpigkzmrdawdjuefotxbh
qcnnnvpigkzmrdzwljuefotxbh
qcsnyvpivkumrdailjuefotxbh
qcsnyvpigkzmrdswljuzfotxbz
qcscynpigkzmrdawljuefotxbc
qeanyvpigkzmrdawijuefotxbh
qclnylpigkzmrdawljuefotxyh
qcsnyvpigkzmrdawljbefowxbp
qcsnyvpagkzmrdawljuefolebh
qxsiyvpigkzmrdawljuefotxgh
qcsnyvpigkynrdawljuefoqxbh
qcsnevpigkzmrdxwgjuefotxbh
qcsnyvpdgkzlrdawljeefotxbh
qcsnyvpigkzmrgawljxbfotxbh
ecsnyvpigkzmrdbwbjuefotxbh
qcsnyvpigkzmraawujuefocxbh
qcsnyvpihkzmrdawljuefouxbn
fgsqyvpigkzmrdawljuefotxbh
qcsnyvpigkmmrdawajuefotnbh
qcsnyvvigkzmrdahljudfotxbh
qcsnyvpixkzmrdqwljutfotxbh
ncsnyvpickzmrdawljuehotxbh
qcsnyvpizkzmrdawlpuefotxbp
wcsnyvfigkzmrdakljuefotxbh
qcsnyvpigkznrdhwljupfotxbh
jcsnyvpigkpmzdawljuefotxbh
qcsnyppigkkmrdawljujfotxbh
qcsnyvpigkumrdaeljuefodxbh
qcsnyvhigkzmrdrwljuefodxbh
qcsnyvpigkacrdawtjuefotxbh
qcsnyvpigkzmylawlquefotxbh`

let labelArray = input.split('\n');

function match(labels) {
    for (let i = 0; i < labels.length; i++) {
        let id1 = labels[i];
        for (let j = i+1; j < labels.length; j++) {
            let id2 = labels[j];
            let diff = 0;
            for (let char = 0; char < id1.length; char++) {
                if (id1[char] !== id2[char]) {
                    diff += 1;
                    if (diff > 1) {
                        char = 26;
                    }
                }
            }
            if (diff === 1) {
                let matchArr = [];
                let id1Arr = id1.split('');
                let id2Arr = id2.split('');
                for (let i = 0; i < id1.length; i++) {
                    if (id1Arr[i] === id2Arr[i]) {
                        matchArr.push(id1Arr[i]);
                    }
                    
                }
                console.log(matchArr.toString());
            }
            }
        }
    
    }

match(labelArray);